import React, { useState } from 'react';
import { useLanguage } from "@/contexts/language-context";
import { Plus, Minus } from "lucide-react";
import { parseDualLanguage } from "@/lib/content-parser";

interface FAQItem {
  question: string;
  answer: string;
}

export function FAQSection({ data = {} }: { data?: Record<string, string> }) {
  const { language } = useLanguage();
  const [openIndex, setOpenIndex] = useState<number | null>(null);

  const toggleFAQ = (index: number) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  const faqData: Record<"EN" | "ID", FAQItem[]> = {
    EN: [
      {
        question: parseDualLanguage(data.faq1Question, 'EN', "Does Ruka Studio handle construction or only design?"),
        answer: parseDualLanguage(data.faq1Answer, 'EN', "We focus on architectural consultancy and engineering planning (architecture, structure, MEP, and working drawings). For physical construction, we recommend our trusted contractor partners and provide regular on-site supervision to ensure execution matches the planning documents.")
      },
      {
        question: parseDualLanguage(data.faq2Question, 'EN', "Where is Ruka Studio's service coverage area?"),
        answer: parseDualLanguage(data.faq2Answer, 'EN', "Our chambers are based in Lombok and Bandung, but we serve architectural planning projects across Indonesia. For out-of-town commissions, site inspections and design consultations are managed efficiently through digital tools and planned site visits.")
      },
      {
        question: parseDualLanguage(data.faq3Question, 'EN', "What is the typical design timeline?"),
        answer: parseDualLanguage(data.faq3Answer, 'EN', "The planning timeline ranges from 1 to 3 months depending on topography complexity and overall floor area. This window covers concept ideation, schematic layouts, structural calculations, and final detailed engineering drawings (DED) ready for construction.")
      },
      {
        question: parseDualLanguage(data.faq4Question, 'EN', "How is the design consultancy fee calculated?"),
        answer: parseDualLanguage(data.faq4Answer, 'EN', "Our fees are calculated transparently, based on the projected floor area (per square meter) or structured as a percentage of construction value for larger institutional/commercial commissions. We provide detailed fee breakdowns before work starts.")
      },
      {
        question: parseDualLanguage(data.faq5Question, 'EN', "Do you assist in obtaining building permits (IMB/PBG)?"),
        answer: parseDualLanguage(data.faq5Answer, 'EN', "Yes. All design packages generated by our studio are prepared to comply with national engineering standards, fully satisfying the requirements needed for building permit submission (IMB/PBG) by either the client or local authorities.")
      }
    ],
    ID: [
      {
        question: parseDualLanguage(data.faq1Question, 'ID', "Apakah Ruka Studio melayani pembangunan fisik atau hanya jasa desain?"),
        answer: parseDualLanguage(data.faq1Answer, 'ID', "Kami berfokus penuh sebagai konsultan & perencana konstruksi (arsitektur, struktur, MEP, dan gambar kerja detail). Untuk pelaksanaan fisik pembangunan, kami dapat merekomendasikan kontraktor rekanan tepercaya dan mendampingi Anda melalui pengawasan berkala agar hasil konstruksi presisi sesuai rencana.")
      },
      {
        question: parseDualLanguage(data.faq2Question, 'ID', "Di mana saja jangkauan wilayah proyek Ruka Studio?"),
        answer: parseDualLanguage(data.faq2Answer, 'ID', "Studio fisik kami berada di Lombok dan Bandung, namun kami melayani perancangan arsitektur di seluruh wilayah Indonesia. Untuk proyek luar kota, koordinasi desain dilakukan secara terstruktur melalui media digital dikombinasikan dengan pengawasan langsung ke lokasi sesuai kesepakatan kontrak.")
      },
      {
        question: parseDualLanguage(data.faq3Question, 'ID', "Berapa lama estimasi waktu pengerjaan dokumen desain?"),
        answer: parseDualLanguage(data.faq3Answer, 'ID', "Waktu perencanaan bervariasi antara 1 hingga 3 bulan tergantung kompleksitas lahan (kontur tebing) dan luasan bangunan. Durasi ini mencakup tahap penyusunan konsep, pengembangan desain detail, kalkulasi struktur, hingga penyusunan Gambar Kerja Detail (DED).")
      },
      {
        question: parseDualLanguage(data.faq4Question, 'ID', "Bagaimana sistem perhitungan biaya jasa arsitek di Ruka Studio?"),
        answer: parseDualLanguage(data.faq4Answer, 'ID', "Biaya perencanaan kami dihitung secara transparan berbasis luas lantai bangunan (per meter persegi) atau berupa persentase tertentu dari rencana nilai konstruksi untuk proyek skala besar. Penawaran biaya akan disesuaikan dengan tingkat kesulitan lahan di lapangan.")
      },
      {
        question: parseDualLanguage(data.faq5Question, 'ID', "Apakah dokumen dari Ruka Studio bisa digunakan untuk mengurus IMB/PBG?"),
        answer: parseDualLanguage(data.faq5Answer, 'ID', "Ya. Setiap output perencanaan dari kami dilengkapi dokumen teknis berstandar nasional yang lengkap, siap diajukan untuk kebutuhan izin mendirikan bangunan (IMB/PBG) baik oleh klien secara mandiri maupun dibantu agen pengurus setempat.")
      }
    ]
  };

  const items = faqData[language];

  return (
    <section
      id="faq-section"
      className="py-[120px] relative overflow-hidden"
      style={{ backgroundColor: "#FCFAF6", borderTop: "1px solid rgba(10,6,8,0.06)" }}
    >
      <div className="max-w-[1000px] mx-auto px-6 md:px-14 relative z-10">
        {/* Section Header */}
        <div className="mb-16 text-center md:text-left">
          <p
            className="uppercase font-semibold mb-6"
            style={{
              fontSize: "10px",
              letterSpacing: "0.35em",
              fontFamily: "var(--font-montserrat, sans-serif)",
              color: "#A4855C",
            }}
          >
            {parseDualLanguage(data.faqEyebrow, language, language === 'EN' ? "COMMON QUESTIONS" : "PERTANYAAN UMUM")}
          </p>
          <h2
            className="font-bold mb-4"
            style={{
              fontSize: "clamp(32px, 4vw, 48px)",
              lineHeight: 1.1,
              letterSpacing: "-0.02em",
              fontFamily: "var(--font-cinzel, serif)",
              color: "#0B2240",
            }}
          >
            {parseDualLanguage(data.faqTitle, language, language === 'EN' ? "Frequently asked." : "Yang sering ditanyakan.")}
          </h2>
          <p
            style={{
              fontSize: "16px",
              lineHeight: 1.6,
              fontWeight: 400,
              fontFamily: "var(--font-montserrat, sans-serif)",
              color: "rgba(10,6,8,0.55)",
            }}
          >
            {parseDualLanguage(
              data.faqDesc, 
              language, 
              language === 'EN' 
                ? "Everything you need to know about starting your architectural journey with us." 
                : "Semua hal yang perlu Anda ketahui sebelum merencanakan hunian impian bersama kami."
            )}
          </p>
        </div>

        {/* Accordion items */}
        <div className="divide-y divide-[#0B2240]/10 border-t border-b border-[#0B2240]/10">
          {items.map((item, index) => {
            const isOpen = openIndex === index;
            return (
              <div key={index} className="py-5 md:py-6 transition-colors duration-200">
                <button
                  onClick={() => toggleFAQ(index)}
                  className="w-full flex items-center justify-between text-left group cursor-pointer focus:outline-none"
                  aria-expanded={isOpen}
                >
                  <h3
                    style={{
                      fontSize: "clamp(15px, 2vw, 18px)",
                      fontFamily: "var(--font-montserrat, sans-serif)",
                      color: isOpen ? "#A4855C" : "#0B2240",
                      fontWeight: 600,
                    }}
                    className="transition-colors duration-300 pr-4"
                  >
                    {item.question}
                  </h3>
                  <span className="flex-shrink-0 text-[#0B2240] group-hover:text-[#A4855C] transition-colors duration-300">
                    {isOpen ? <Minus className="w-5 h-5" /> : <Plus className="w-5 h-5" />}
                  </span>
                </button>

                {/* Animated collapse/expand content container */}
                <div
                  className={`grid transition-all duration-300 ease-in-out ${
                    isOpen ? "grid-rows-[1fr] opacity-100 mt-4" : "grid-rows-[0fr] opacity-0"
                  }`}
                >
                  <div className="overflow-hidden">
                    <p
                      style={{
                        fontSize: "14px",
                        lineHeight: 1.6,
                        fontFamily: "var(--font-montserrat, sans-serif)",
                        color: "rgba(10,6,8,0.7)",
                      }}
                      className="max-w-4xl"
                    >
                      {item.answer}
                    </p>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
}
